"""add hero_slides

Revision ID: 1039aa3784eb
Revises: 460bc34f30de
Create Date: 2026-05-26 20:05:02.898214
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1039aa3784eb'
down_revision: Union[str, None] = '460bc34f30de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_slides',
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_slides_is_active'), 'hero_slides', ['is_active'], unique=False)
    op.create_index('ix_hero_slides_is_active_sort_order', 'hero_slides', ['is_active', 'sort_order'], unique=False)
    op.create_index(op.f('ix_hero_slides_sort_order'), 'hero_slides', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hero_slides_sort_order'), table_name='hero_slides')
    op.drop_index('ix_hero_slides_is_active_sort_order', table_name='hero_slides')
    op.drop_index(op.f('ix_hero_slides_is_active'), table_name='hero_slides')
    op.drop_table('hero_slides')
    # ### end Alembic commands ###
